return {
    "mason-org/mason.nvim",
    opts = {
        ensure_installed = {
            "stylua",
            "shellcheck",
            "shfmt",
            "bash-language-server",
            "codebook",
            "clangd",
            "cmakelang",
            "cmakelint",
            "codelldb",
            "cpplint",
            "css-lsp",
            "css-variables-language-server",
            "cssmodules-language-server",
            "debugpy",
            "docker-compose-language-service",
            "dockerfile-language-server",
            "eslint_d",
            "hadolint",
            "html-lsp",
            "js-debug-adapter",
            "json-lsp",
            "lua-language-server",
            "markdown-toc",
            "markdownlint-cli2",
            "marksman",
            "oxfmt",
            -- "pyright",
            "ruff",
            "rust-analyzer",
            "sqlfluff",
            "taplo",
            "tree-sitter-cli",
            "vtsls",
            "vue-language-server",
            "yaml-language-server",
            "zuban",
            "tsp-server",
            -- "go-debug-adapter",
            -- "gofumpt",
            -- "goimports",
            -- "golangci-lint",
            -- "golines",
            -- "gomodifytags",
            -- "gopls",
            -- "gotests",
            -- "gotestsum",
            -- "delve",
        },
    },
}
